import multiprocessing as mp

SHELL = "/bin/bash"
"""Path to the shell program."""

BUILD_SCRIPT_NAME = "build.sh"
"""Name of the subjects' build script."""

FLAWFINDER = "/opt/flawfinder-2.0.19/flawfinder.py"
"""Path to the Flawfinder analyzer."""

FLAWFINDER_FLAG_SET = ["--falsepositive", "--minlevel=3", "--neverignore"]
"""Flags of Flawfinder."""

INFER = "/opt/infer-1.1.0/bin/infer"
"""Path to the Infer analyzer."""

INFER_RULE_SET = [
    "--no-default-checkers",
    "--biabduction",
    "--bufferoverrun",
    # "--liveness",
    "--pulse",
    # "--quandary",
    # "--racerd",
    "--siof",
    # "--starvation",
    "--uninit"
]
"""Flags/checks of Infer."""

INFER_NUM_THREADS = mp.cpu_count() - 1
"""Number of threads used by Infer."""

CODEQL = "/opt/codeql-2.12.0/cli/codeql"
"""Path to the CodeQL analyzer."""

CODEQL_LIB_ROOT = "/opt/codeql-2.12.0/lib"
"""Path to the CodeQL library directory root."""

# TODO: Filter out relevant CodeQL rules!
CODEQL_RULE_SET = [
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/AlertSuppression.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Architecture/FeatureEnvy.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Architecture/General\ Class-Level\ Information/ClassHierarchies.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Architecture/General\ Class-Level\ Information/HubClasses.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Architecture/General\ Class-Level\ Information/InheritanceDepthDistribution.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Architecture/General\ Namespace-Level\ Information/CyclicNamespaces.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Architecture/General\ Namespace-Level\ Information/GlobalNamespaceClasses.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Architecture/General\ Namespace-Level\ Information/NamespaceDependencies.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Architecture/General\ Top-Level\ Information/GeneralStatistics.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Architecture/InappropriateIntimacy.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Architecture/Refactoring\ Opportunities/ClassesWithManyDependencies.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Architecture/Refactoring\ Opportunities/ClassesWithManyFields.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Architecture/Refactoring\ Opportunities/ComplexFunctions.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Architecture/Refactoring\ Opportunities/CyclomaticComplexity.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Architecture/Refactoring\ Opportunities/FunctionsWithManyParameters.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/BlockWithTooManyStatements.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/ComplexCondition.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Exceptions/AccidentalRethrow.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Exceptions/CatchingByValue.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Exceptions/LeakyCatch.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Exceptions/ThrowingPointers.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Hiding/DeclarationHidesParameter.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Hiding/DeclarationHidesVariable.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Hiding/LocalVariableHidesGlobalVariable.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Likely\ Errors/CommaBeforeMisleadingIndentation.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Likely\ Errors/EmptyBlock.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Likely\ Errors/OffsetUseBeforeRangeCheck.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Likely\ Errors/Slicing.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Magic\ Constants/JapaneseEraDate.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Magic\ Constants/MagicConstantsNumbers.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Magic\ Constants/MagicConstantsString.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Magic\ Constants/MagicNumbersUseConstant.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Magic\ Constants/MagicStringsUseConstant.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/NVI.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/NVIHub.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/RuleOfThree.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/RuleOfTwo.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/SloppyGlobal.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/SwitchLongCase.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Unused\ Entities/UnusedIncludes.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Unused\ Entities/UnusedLocals.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Unused\ Entities/UnusedStaticFunctions.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/Unused\ Entities/UnusedStaticVariables.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Best\ Practices/UseOfGoto.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/DeadCodeCondition.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/DeadCodeFunction.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/DeadCodeGoto.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/DescriptorMayNotBeClosed.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/DescriptorNeverClosed.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/FileMayNotBeClosed.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/FileNeverClosed.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/GlobalUseBeforeInit.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/InconsistentNullnessTesting.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/InitialisationNotRun.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/LargeParameter.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/LateNegativeTest.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/MemoryMayNotBeFreed.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/MemoryNeverFreed.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/MissingCheckScanf.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/MissingNegativityTest.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/MissingNullTest.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/NewArrayDeleteMismatch.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/NewDeleteArrayMismatch.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/NewFreeMismatch.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/NotInitialised.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/OverflowCalculated.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/OverflowDestination.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/OverflowStatic.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/ReturnStackAllocatedObject.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/ReturnValueIgnored.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/SizeCheck.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/SizeCheck2.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/Unused.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Critical/UseAfterFree.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/definitions.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Diagnostics/ExtractionWarnings.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Diagnostics/FailedExtractorInvocations.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Diagnostics/Internal/ExtractionErrors.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Diagnostics/SuccessfullyExtractedFiles.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Documentation/CommentedOutCode.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Documentation/DocumentApi.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Documentation/FixmeComments.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Documentation/TodoComments.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Documentation/UncommentedFunction.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Best\ Practices/UselessTest.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Best\ Practices/WrongUintAccess.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Likely\ Bugs/ArrayAccessProductFlow.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Likely\ Bugs/OverrunWriteProductFlow.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Likely\ Bugs/RedundantNullCheckParam.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-020/LateCheckOfFunctionArgument.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-020/NoCheckBeforeUnsafePutUser.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-078/WordexpTainted.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-1041/FindWrapperFunctions.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-1126/DeclarationOfVariableWithUnnecessarilyWideScope.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-120/MemoryUnsafeFunctionScan.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-125/DangerousWorksWithMultibyteOrWideCharacters.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-190/AllocMultiplicationOverflow.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-190/DangerousUseOfTransformationAfterOperation.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-193/ConstantSizeArrayOffByOne.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-193/InvalidPointerDeref.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-200/ExposureSensitiveInformationUnauthorizedActor.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-243/IncorrectChangingWorkingDirectory.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-266/IncorrectPrivilegeAssignment.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-273/PrivilegeDroppingOutoforder.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-285/PamAuthorization.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-359/PrivateCleartextWrite.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-362/double-fetch.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-377/InsecureTemporaryFile.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-401/MemoryLeakOnFailedCallToRealloc.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-415/DoubleFree.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-476/DangerousUseOfExceptionBlocks.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-561/FindIncorrectlyUsedSwitch.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-670/DangerousUseSSL_shutdown.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-675/DoubleRelease.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-691/InsufficientControlFlowManagementAfterRefactoringTheCode.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-691/InsufficientControlFlowManagementWhenUsingBitOperations.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-703/FindIncorrectlyUsedExceptions.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-754/ImproperCheckReturnValueScanf.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-758/UndefinedOrImplementationDefinedBehavior.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-783/OperatorPrecedenceLogicErrorWhenUseBitwiseOrLogicalOperations.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-783/OperatorPrecedenceLogicErrorWhenUseBoolType.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-787/UnsignedToSignedPointerArith.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/experimental/Security/CWE/CWE-788/AccessOfMemoryLocationAfterEndOfBufferUsingStrlen.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/external/examples/filters/BumpMetricBy10.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/external/examples/filters/EditDefectMessage.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/external/examples/filters/ExcludeGeneratedCode.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/filters/ClassifyFiles.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Header\ Cleanup/Cleanup-DuplicateIncludeGuard.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-2/Rule\ 03/ExitNonterminatingLoop.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-2/Rule\ 03/LoopBounds.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-2/Rule\ 04/Recursion.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-2/Rule\ 05/HeapMemory.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-2/Rule\ 07/ThreadSafety.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-2/Rule\ 09/AvoidNestedSemaphores.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-2/Rule\ 09/AvoidSemaphores.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-2/Rule\ 09/OutOfOrderLocks.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-2/Rule\ 09/ReleaseLocksWhenAcquired.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-2/Rule\ 11/SimpleControlFlowGoto.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-2/Rule\ 11/SimpleControlFlowJmp.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-2/Rule\ 12/EnumInitialization.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-3/Rule\ 13/ExternDeclsInHeader.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-3/Rule\ 13/LimitedScopeFile.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-3/Rule\ 13/LimitedScopeFunction.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-3/Rule\ 13/LimitedScopeLocalHidesGlobal.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-3/Rule\ 14/CheckingReturnValues.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-3/Rule\ 15/CheckingParameterValues.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-3/Rule\ 16/UseOfAssertionsConstant.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-3/Rule\ 16/UseOfAssertionsDensity.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-3/Rule\ 16/UseOfAssertionsNonBoolean.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-3/Rule\ 16/UseOfAssertionsSideEffect.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-3/Rule\ 17/BasicIntTypes.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-3/Rule\ 18/CompoundExpressions.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-3/Rule\ 19/NoBooleanSideEffects.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-4/Rule\ 20/PreprocessorUse.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-4/Rule\ 20/PreprocessorUseIfdef.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-4/Rule\ 20/PreprocessorUsePartial.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-4/Rule\ 20/PreprocessorUseUndisciplined.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-4/Rule\ 21/MacroInBlock.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-4/Rule\ 22/UseOfUndef.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-4/Rule\ 23/MismatchedIfdefs.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-4/Rule\ 24/MultipleStmtsPerLine.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-4/Rule\ 24/MultipleVarDeclsPerLine.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-4/Rule\ 25/FunctionSizeLimits.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-4/Rule\ 26/DeclarationPointerNesting.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-4/Rule\ 27/PointerDereferenceInStmt.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-4/Rule\ 28/HiddenPointerDereferenceMacro.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-4/Rule\ 28/HiddenPointerIndirectionTypedef.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-4/Rule\ 29/NonConstFunctionPointer.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-4/Rule\ 30/FunctionPointerConversions.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/JPL_C/LOC-4/Rule\ 31/IncludesFirst.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/3.02\ Code\ Size\ and\ Complexity/AV\ Rule\ 1.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/3.02\ Code\ Size\ and\ Complexity/AV\ Rule\ 2.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/3.02\ Code\ Size\ and\ Complexity/AV\ Rule\ 3.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.04\ Environment/AV\ Rule\ 11.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.04\ Environment/AV\ Rule\ 12.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.04\ Environment/AV\ Rule\ 13.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.04\ Environment/AV\ Rule\ 14.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.04\ Environment/AV\ Rule\ 9.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.05\ Libraries/AV\ Rule\ 17.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.05\ Libraries/AV\ Rule\ 18.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.05\ Libraries/AV\ Rule\ 19.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.05\ Libraries/AV\ Rule\ 20.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.05\ Libraries/AV\ Rule\ 21.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.05\ Libraries/AV\ Rule\ 22.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.05\ Libraries/AV\ Rule\ 23.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.05\ Libraries/AV\ Rule\ 24.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.05\ Libraries/AV\ Rule\ 25.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.06\ Pre-Processing\ Directives/AV\ Rule\ 26.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.06\ Pre-Processing\ Directives/AV\ Rule\ 27.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.06\ Pre-Processing\ Directives/AV\ Rule\ 28.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.06\ Pre-Processing\ Directives/AV\ Rule\ 29.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.06\ Pre-Processing\ Directives/AV\ Rule\ 30.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.06\ Pre-Processing\ Directives/AV\ Rule\ 31.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.06\ Pre-Processing\ Directives/AV\ Rule\ 32.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.07\ Header\ Files/AV\ Rule\ 33.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.07\ Header\ Files/AV\ Rule\ 35.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.07\ Header\ Files/AV\ Rule\ 39.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.08\ Implementation\ Files/AV\ Rule\ 40.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 41.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 42.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 43.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 44.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 45.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 46.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 47.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 48.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 49.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 50.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 51.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 52.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 53.1.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 53.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 54.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 57.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 58.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 59.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 60.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 61.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.09\ Style/AV\ Rule\ 63.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 68.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 69.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 70.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 71.1.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 71.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 73.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 74.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 75.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 76.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 77.1.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 78.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 79.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 81.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 82.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 85.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 88.1.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 88.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 89.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 94.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 95.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 96.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 97.1.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.10\ Classes/AV\ Rule\ 97.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.11\ Namespaces/AV\ Rule\ 99.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.12\ Templates/AV\ Rule\ 104.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.13\ Functions/AV\ Rule\ 107.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.13\ Functions/AV\ Rule\ 108.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.13\ Functions/AV\ Rule\ 110.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.13\ Functions/AV\ Rule\ 111.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.13\ Functions/AV\ Rule\ 113.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.13\ Functions/AV\ Rule\ 114.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.13\ Functions/AV\ Rule\ 115.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.13\ Functions/AV\ Rule\ 119.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.14\ Comments/AV\ Rule\ 126.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.14\ Comments/AV\ Rule\ 127.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.14\ Comments/AV\ Rule\ 133.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.15\ Declarations\ and\ Definitions/AV\ Rule\ 135.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.15\ Declarations\ and\ Definitions/AV\ Rule\ 138.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.15\ Declarations\ and\ Definitions/AV\ Rule\ 139.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.15\ Declarations\ and\ Definitions/AV\ Rule\ 140.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.16\ Initialization/AV\ Rule\ 142.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.16\ Initialization/AV\ Rule\ 143.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.16\ Initialization/AV\ Rule\ 145.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.17\ Types/AV\ Rule\ 147.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.17\ Types/AV\ Rule\ 148.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.18\ Constants/AV\ Rule\ 149.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.18\ Constants/AV\ Rule\ 150.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.18\ Constants/AV\ Rule\ 151.1.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.18\ Constants/AV\ Rule\ 151.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.19\ Variables/AV\ Rule\ 152.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.20\ Unions\ and\ Bit\ Fields/AV\ Rule\ 153.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.20\ Unions\ and\ Bit\ Fields/AV\ Rule\ 154.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.20\ Unions\ and\ Bit\ Fields/AV\ Rule\ 155.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.20\ Unions\ and\ Bit\ Fields/AV\ Rule\ 156.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.21\ Operators/AV\ Rule\ 157.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.21\ Operators/AV\ Rule\ 158.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.21\ Operators/AV\ Rule\ 159.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.21\ Operators/AV\ Rule\ 160.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.21\ Operators/AV\ Rule\ 162.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.21\ Operators/AV\ Rule\ 163.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.21\ Operators/AV\ Rule\ 164.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.21\ Operators/AV\ Rule\ 165.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.21\ Operators/AV\ Rule\ 166.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.21\ Operators/AV\ Rule\ 168.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.22\ Pointers\ and\ References/AV\ Rule\ 170.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.22\ Pointers\ and\ References/AV\ Rule\ 171.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.22\ Pointers\ and\ References/AV\ Rule\ 173.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.22\ Pointers\ and\ References/AV\ Rule\ 175.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.22\ Pointers\ and\ References/AV\ Rule\ 176.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.23\ Type\ Conversions/AV\ Rule\ 178.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.23\ Type\ Conversions/AV\ Rule\ 179.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.23\ Type\ Conversions/AV\ Rule\ 180.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.23\ Type\ Conversions/AV\ Rule\ 181.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.23\ Type\ Conversions/AV\ Rule\ 182.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.23\ Type\ Conversions/AV\ Rule\ 184.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.23\ Type\ Conversions/AV\ Rule\ 185.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.24\ Control\ Flow\ Structures/AV\ Rule\ 186.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.24\ Control\ Flow\ Structures/AV\ Rule\ 187.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.24\ Control\ Flow\ Structures/AV\ Rule\ 188.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.24\ Control\ Flow\ Structures/AV\ Rule\ 189.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.24\ Control\ Flow\ Structures/AV\ Rule\ 190.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.24\ Control\ Flow\ Structures/AV\ Rule\ 191.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.24\ Control\ Flow\ Structures/AV\ Rule\ 192.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.24\ Control\ Flow\ Structures/AV\ Rule\ 193.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.24\ Control\ Flow\ Structures/AV\ Rule\ 194.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.24\ Control\ Flow\ Structures/AV\ Rule\ 195.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.24\ Control\ Flow\ Structures/AV\ Rule\ 196.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.24\ Control\ Flow\ Structures/AV\ Rule\ 197.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.24\ Control\ Flow\ Structures/AV\ Rule\ 198.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.24\ Control\ Flow\ Structures/AV\ Rule\ 199.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.24\ Control\ Flow\ Structures/AV\ Rule\ 200.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.24\ Control\ Flow\ Structures/AV\ Rule\ 201.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.25\ Expressions/AV\ Rule\ 202.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.25\ Expressions/AV\ Rule\ 204.1.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.25\ Expressions/AV\ Rule\ 204.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.25\ Expressions/AV\ Rule\ 205.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.26\ Memory\ Allocation/AV\ Rule\ 206.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.26\ Memory\ Allocation/AV\ Rule\ 207.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.27\ Fault\ Handling/AV\ Rule\ 208.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.28\ Portable\ Code/AV\ Rule\ 209.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.28\ Portable\ Code/AV\ Rule\ 210.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.28\ Portable\ Code/AV\ Rule\ 212.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.28\ Portable\ Code/AV\ Rule\ 213.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.28\ Portable\ Code/AV\ Rule\ 214.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/jsf/4.28\ Portable\ Code/AV\ Rule\ 215.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/AmbiguouslySignedBitField.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Arithmetic/BadAdditionOverflowCheck.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Arithmetic/BadCheckOdd.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Arithmetic/BitwiseSignCheck.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Arithmetic/ComparisonPrecedence.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Arithmetic/ComparisonWithCancelingSubExpr.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Arithmetic/FloatComparison.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Arithmetic/IntMultToLong.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Arithmetic/PointlessComparison.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Arithmetic/PointlessSelfComparison.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Arithmetic/SignedOverflowCheck.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Arithmetic/UnsignedGEZero.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/ContinueInFalseLoop.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Conversion/ArrayArgSizeMismatch.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Conversion/CastArrayPointerArithmetic.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Conversion/ConversionChangesSign.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Conversion/ImplicitDowncastFromBitfield.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Conversion/LossyFunctionResultCast.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Conversion/LossyPointerCast.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Conversion/NonzeroValueCastToPointer.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Format/NonConstantFormat.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Format/SnprintfOverflow.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Format/TooManyFormatArguments.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Format/WrongNumberOfFormatArguments.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Format/WrongTypeFormatArguments.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/InconsistentCallOnResult.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/InconsistentCheckReturnNull.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/JapaneseEra/ConstructorOrMethodWithExactEraDate.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/JapaneseEra/StructWithExactEraDate.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Leap\ Year/Adding365DaysPerYear.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Leap\ Year/UncheckedLeapYearAfterYearModification.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Leap\ Year/UncheckedReturnValueForTimeFunctions.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Leap\ Year/UnsafeArrayForDaysOfYear.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Likely\ Typos/AssignWhereCompareMeant.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Likely\ Typos/BoolValueInBitOp.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Likely\ Typos/CompareWhereAssignMeant.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Likely\ Typos/DubiousNullCheck.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Likely\ Typos/ExprHasNoEffect.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Likely\ Typos/FutileConditional.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Likely\ Typos/inconsistentLoopDirection.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Likely\ Typos/IncorrectNotOperatorUsage.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Likely\ Typos/LogicalExprCouldBeSimplified.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Likely\ Typos/MissingEnumCaseInSwitch.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Likely\ Typos/ShortCircuitBitMask.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Likely\ Typos/UsingStrcpyAsBoolean.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/AllocaInLoop.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/ImproperNullTermination.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/NtohlArrayNoBound.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/Padding/More64BitWaste.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/Padding/NonPortablePrintf.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/Padding/Suboptimal64BitType.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/PointerOverflow.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/PotentialBufferOverflow.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/ReturnCstrOfLocalStdString.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/ReturnStackAllocatedMemory.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/StackAddressEscapes.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/StrncpyFlippedArgs.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/SuspiciousCallToMemset.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/SuspiciousCallToStrncat.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/SuspiciousSizeof.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/UninitializedLocal.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/UnsafeUseOfStrcat.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Memory\ Management/UsingExpiredStackAddress.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/NestedLoopSameVar.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/OO/IncorrectConstructorDelegation.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/OO/NonVirtualDestructor.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/OO/NonVirtualDestructorInBaseClass.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/OO/SelfAssignmentCheck.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/OO/ThrowInDestructor.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/OO/UnsafeUseOfThis.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/OO/VirtualCallInStructor.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Protocols/TlsSettingsMisconfiguration.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Protocols/UseOfDeprecatedHardcodedProtocol.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/RedundantNullCheckSimple.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/ReturnConstType.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/ReturnConstTypeMember.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/ShortLoopVarName.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Underspecified\ Functions/ImplicitFunctionDeclaration.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Underspecified\ Functions/MistypedFunctionArguments.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Underspecified\ Functions/TooFewArguments.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/Underspecified\ Functions/TooManyArguments.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Likely\ Bugs/UseInOwnInitializer.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CAfferentCoupling.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CEfferentCoupling.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CHalsteadBugs.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CHalsteadDifficulty.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CHalsteadEffort.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CHalsteadLength.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CHalsteadVocabulary.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CHalsteadVolume.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CInheritanceDepth.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CLackOfCohesionCK.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CLackOfCohesionHS.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CLinesOfCode.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CNumberOfFields.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CNumberOfFunctions.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CNumberOfStatements.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CPercentageOfComplexCode.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CResponse.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CSizeOfAPI.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Classes/CSpecialisation.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Dependencies/ExternalDependencies.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Dependencies/ExternalDependenciesSourceLinks.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/External/FileCompilationDisplayStrings.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/External/FileCompilationSourceLinks.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/AutogeneratedLOC.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/ConditionalSegmentConditions.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/ConditionalSegmentLines.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FAfferentCoupling.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FCommentRatio.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FCyclomaticComplexity.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FDirectIncludes.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FEfferentCoupling.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FHalsteadBugs.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FHalsteadDifficulty.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FHalsteadEffort.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FHalsteadLength.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FHalsteadVocabulary.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FHalsteadVolume.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FLines.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FLinesOfCode.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FLinesOfCommentedOutCode.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FLinesOfComments.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FMacroRatio.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FNumberOfClasses.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FNumberOfTests.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FTimeInFrontend.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FTodoComments.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FTransitiveIncludes.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FTransitiveSourceIncludes.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/FunctionLength.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/NumberOfFunctions.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/NumberOfGlobals.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/NumberOfParameters.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/NumberOfPublicFunctions.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Files/NumberOfPublicGlobals.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Functions/FunCyclomaticComplexity.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Functions/FunIterationNestingDepth.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Functions/FunLinesOfCode.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Functions/FunLinesOfComments.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Functions/FunNumberOfCalls.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Functions/FunNumberOfParameters.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Functions/FunNumberOfStatements.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Functions/FunPercentageOfComments.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Functions/StatementNestingDepth.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Internal/CallableDisplayStrings.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Internal/CallableExtents.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Internal/CallableSourceLinks.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Internal/DiagnosticsSumElapsedTimes.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Internal/IRConsistency.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Internal/ReftypeDisplayStrings.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Internal/ReftypeSourceLinks.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Namespaces/AbstractNamespaces.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Namespaces/ConcreteNamespaces.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Namespaces/HighAfferentCouplingNamespaces.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Namespaces/HighDistanceFromMainLineNamespaces.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Namespaces/HighEfferentCouplingNamespaces.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Namespaces/StableNamespaces.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Metrics/Namespaces/UnstableNamespaces.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Microsoft/CallWithNullSAL.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Microsoft/IgnoreReturnValueSAL.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Microsoft/InconsistentSAL.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/PointsTo/Debug.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/PointsTo/PreparedStagedPointsTo.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/PointsTo/Stats.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/PointsTo/TaintedFormatStrings.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 1/UseOfGoto.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 1/UseOfJmp.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 1/UseOfRecursion.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 2/BoundedLoopIterations.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 2/ExitPermanentLoop.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 3/DynamicAllocAfterInit.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 4/FunctionTooLong.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 4/OneStmtPerLine.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 5/AssertionDensity.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 5/AssertionSideEffect.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 5/ConstantAssertion.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 5/NonBooleanAssertion.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 6/GlobalCouldBeStatic.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 6/VariableScopeTooLarge.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 7/CheckArguments.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 7/CheckReturnValues.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 8/AvoidConditionalCompilation.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 8/PartialMacro.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 8/RestrictPreprocessor.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 8/UndisciplinedMacro.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 9/FunctionPointer.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 9/HiddenPointerIndirection.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Power\ of\ 10/Rule\ 9/PointerNesting.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-014/MemsetMayBeDeleted.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-020/CountUntrustedDataToExternalAPI.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-020/IRCountUntrustedDataToExternalAPI.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-020/IRUntrustedDataToExternalAPI.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-020/UntrustedDataToExternalAPI.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-022/TaintedPath.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-078/ExecTainted.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-079/CgiXss.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-089/SqlTainted.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-114/UncontrolledProcessOperation.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-119/OverflowBuffer.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-120/BadlyBoundedWrite.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-120/OverrunWrite.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-120/OverrunWriteFloat.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-120/UnboundedWrite.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-120/VeryLikelyOverrunWrite.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-121/UnterminatedVarargsCall.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-129/ImproperArrayIndexValidation.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-131/NoSpaceForZeroTerminator.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-134/UncontrolledFormatString.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-134/UncontrolledFormatStringThroughGlobalVar.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-170/ImproperNullTerminationTainted.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-190/ArithmeticTainted.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-190/ArithmeticUncontrolled.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-190/ArithmeticWithExtremeValues.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-190/ComparisonWithWiderType.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-190/IntegerOverflowTainted.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-190/TaintedAllocationSize.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-191/UnsignedDifferenceExpressionComparedZero.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-253/HResultBooleanConversion.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-290/AuthenticationBypass.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-295/SSLResultConflation.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-295/SSLResultNotChecked.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-311/CleartextBufferWrite.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-311/CleartextFileWrite.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-311/CleartextTransmission.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-313/CleartextSqliteDatabase.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-319/UseOfHttp.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-326/InsufficientKeySize.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-327/BrokenCryptoAlgorithm.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-327/OpenSslHeartbleed.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-367/TOCTOUFilesystemRace.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-428/UnsafeCreateProcessCall.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-457/ConditionallyUninitializedVariable.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-468/IncorrectPointerScaling.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-468/IncorrectPointerScalingChar.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-468/IncorrectPointerScalingVoid.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-468/SuspiciousAddWithSizeof.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-497/ExposedSystemData.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-497/PotentiallyExposedSystemData.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-570/IncorrectAllocationErrorHandling.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-611/XXE.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-676/DangerousFunctionOverflow.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-676/DangerousUseOfCin.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-676/PotentiallyDangerousFunction.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-704/WcharCharConversion.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-732/DoNotCreateWorldWritable.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-732/OpenCallMissingModeArgument.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-732/UnsafeDaclSecurityDescriptor.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-764/LockOrderCycle.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-764/TwiceLocked.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-764/UnreleasedLock.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-807/TaintedCondition.ql",
    f"{CODEQL_LIB_ROOT}/cpp/ql/src/Security/CWE/CWE-835/InfiniteLoopWithUnsatisfiableExitCondition.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Summary/LinesOfCode.ql",
    # f"{CODEQL_LIB_ROOT}/cpp/ql/src/Summary/LinesOfUserCode.ql"
]
"""Queries (checks) of CodeQL."""

CODEQL_NUM_THREADS = mp.cpu_count() - 1
"""Number of threads used by CodeQL."""
