# SPDX-FileCopyrightText: 2023 Stephan Lipp, Technical University of Munich (TUM), et al.
# SPDX-License-Identifier: Apache-2.0
name: Check Reuse

on:
  push:

permissions:
  contents: read

jobs:
  deploy:
    container:
      image: tumi4/python-3.9-bullseye-poetry-1.2.1
      options: --user 1001
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build package
      run: |
        cd src/static_analysis/sast
        poetry install
        poetry run reuse lint
